In [1]:
import cv2, utils
import numpy as np
import matplotlib.pyplot as plt
import gaussian_filter
import convolution
import time

In [2]:
def normalize_img(arr, min_val, max_val):
    """ min_val ~ max_val normalization """
    min_arr = np.amin(arr)
    max_arr = np.amax(arr)
    if min_arr != max_arr:
        arr = (arr - min_arr) * max_val / (max_arr - min_arr) + min_val
    return arr

In [3]:
def clip_img(arr, min_val, max_val):
    """ min_val ~ max_val clipping """
    arr = np.where(arr < min_val, min_val, arr)
    arr = np.where(arr > max_val, max_val, arr)
    return arr

In [9]:
# convert BGR to YCbCr
def cvtYCrCb(image):
    YCbCr = cv2.cvtColor(image, cv2.COLOR_BGR2YCrCb)
    return YCbCr

In [10]:
# convert YCbCr to BGR
def getBGR(image):
    bgr = cv2.cvtColor(image, cv2.COLOR_YCrCb2BGR)
    return bgr

In [6]:
def unsharp():
    """ week3 assignment 2: unsharp masking and high boost filtering """
    
    # load a image
    image = cv2.imread("../Images/001_blurred.png") # (232, 230, 3)
    cv2.imshow('original', image)
    # convert BGR to YCbCr
    img_cvt = cvtYCrCb(image) # (232, 230, 3)
    # get Y
    old_Y = img_cvt[:, :, 0] # (232, 230)

    for ks in [5, 9, 13]:
        # make a kernel
        gauss_kernel = gaussian_filter.gaussian_2d(None, k_size=(ks,ks), sigma=max(1.0, (ks/4)))

        # convolution performed with the kernel
        # cv2conv returns an output shape of 2 dimension
        filtered_Y = convolution.cv2conv(None, old_Y.copy(), gauss_kernel)
        # unsharp mask
        mask_Y = old_Y - filtered_Y

        # multiplication of boost k
        for k_val in range(2, 4):
            # adding filtered_Y and old_Y
            new_Y = old_Y + k_val * mask_Y
            # clipping
            new_Y = clip_img(new_Y, 0.0, 255.0)
            # type conversion to uint8
            new_Y = new_Y.astype(np.uint8)

            # change the image to a filtered one
            img_cvt[:, :, 0] = new_Y
            image = getBGR(img_cvt)
            img_title = f'unsharp boost; ks={ks} / k={k_val}'
            cv2.imshow(img_title, image)

            img_cvt[:, :, 0] = old_Y
            image = getBGR(img_cvt)
            img_title = f'originial / k={k_val}'
            cv2.imshow(img_title, image)

    # test
    img_cvt[:, :, 0] = old_Y
    image = getBGR(img_cvt)
    cv2.imshow("after", image)

    print("press any key to proceed or press 'q' to quit")
    key = cv2.waitKey(0)
    if True or key == ord('q'):
        return

In [7]:
%xmode Plain

Exception reporting mode: Plain


In [ ]:
%run -d unsharp_masking.py

Breakpoint 1 at /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py:1
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(1)<module>()
1---> 1 import argparse, cv2, utils
      2 import numpy as np
      3 import matplotlib.pyplot as plt
      4 import gaussian_filter
      5 import convolution

ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(2)<module>()
1     1 import argparse, cv2, utils
----> 2 import numpy as np
      3 import matplotlib.pyplot as plt
      4 import gaussian_filter
      5 import convolution

ipdb> 
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(3)<module>()
1     1 import argparse, cv2, utils
      2 import numpy as np
----> 3 import matplotlib.pyplot as plt
      4 import gaussian_filter
      5 import convolution

ipdb> 
> /home/jy/Documents/

ipdb> s
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(37)unsharp()
     35     """ week3 assignment 2: unsharp masking and high boost filtering """
     36 
---> 37     args = get_arguments()
     38     ip = utils.ImageProcessing(args)
     39 

ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(38)unsharp()
     36 
     37     args = get_arguments()
---> 38     ip = utils.ImageProcessing(args)
     39 
     40     # load a image

ipdb> 
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(41)unsharp()
     39 
     40     # load a image
---> 41     image = ip.get_one_image() # (232, 230, 3)
     42     cv2.imshow('original', image)
     43     # convert BGR to YCbCr

ipdb> 
Loading an image: ../Images/001_blurred.png
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(42)unsharp()
     40     # load a image
     41     imag

ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(56)unsharp()
     54         filtered_Y = convolution.cv2conv(None, old_Y.copy(), gauss_kernel)
     55         # unsharp mask
---> 56         mask_Y = old_Y - filtered_Y
     57 
     58         # multiplication of boost k

ipdb> p old_Y
array([[51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       ...,
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51]], dtype=uint8)
ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(59)unsharp()
     57 
     58         # multiplication of boost k
---> 59         for k_val in range(2, 4):
     60             # adding filtered_Y and old_Y
     61             new_Y = old_Y + k_val * mask_Y

ipdb> p old_Y
array([[51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       [51, 5

ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(73)unsharp()
     71             cv2.imshow(img_title, image)
     72 
---> 73             img_cvt[:, :, 0] = old_Y
     74             image = ip.getBGR(img_cvt)
     75             img_title = f'originial / k={k_val}'

ipdb> p old_Y
array([[51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       ...,
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51],
       [51, 51, 51, ..., 51, 51, 51]], dtype=uint8)
ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py(74)unsharp()
     72 
     73             img_cvt[:, :, 0] = old_Y
---> 74             image = ip.getBGR(img_cvt)
     75             img_title = f'originial / k={k_val}'
     76             cv2.imshow(img_title, image)

ipdb> n
> /home/jy/Documents/SMIT/1_1_Image_Processing/code/week3_assignments/unsharp_masking.py