In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
data=pd.read_excel("../data/PM_ML_Data_Final.xlsx",index_col="TestID")

In [3]:
data.head()

WNRD     WNVol     WNNCD    Class
TestID                                       
1       0.000120  0.012339  0.008525  Similar
2       0.000120  0.011953  0.008375  Similar
3       0.000196  0.007618  0.004438  Similar
4       0.000197  0.007452  0.004424  Similar
5       0.000162  0.012785  0.009120  Similar

## Data Split

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
seed=7

In [7]:
X=data.drop('Class',axis=1)
y=data['Class']

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=seed)

## LDA

In [11]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

In [12]:
lda=LDA()

In [13]:
lda.fit(X_train,y_train)

LinearDiscriminantAnalysis()

In [14]:
print(lda.score(X_train,y_train))

0.8284023668639053


## Prediction

In [15]:
lda.predict(X_test)

array(['Different', 'Instrument', 'Instrument', 'Similar', 'Different',
       'Different', 'Different', 'Instrument', 'Different', 'Similar',
       'Instrument', 'Similar', 'Instrument', 'Instrument', 'Similar',
       'Instrument', 'Different', 'Instrument', 'Similar', 'Similar',
       'Similar', 'Instrument', 'Similar', 'Similar', 'Similar',
       'Instrument', 'Different', 'Day', 'Different', 'Different',
       'Different', 'Similar', 'Similar', 'Similar', 'Similar',
       'Different', 'Instrument', 'Similar', 'Similar', 'Different',
       'Similar', 'Similar', 'Similar', 'Similar', 'Instrument',
       'Instrument', 'Similar', 'Different', 'Instrument', 'Instrument',
       'Different', 'Similar', 'Similar', 'Similar', 'Similar',
       'Instrument', 'Different', 'Instrument', 'Different', 'Similar',
       'Different', 'Different', 'Instrument', 'Instrument', 'Similar',
       'Instrument', 'Instrument', 'Instrument', 'Instrument',
       'Instrument', 'Similar', 'Different

## Evaluation

In [19]:
predictions=lda.predict(X_test)

In [20]:
from sklearn.metrics import classification_report,confusion_matrix

In [21]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         Day       0.00      0.00      0.00        35
   Different       1.00      0.89      0.94        80
  Instrument       0.88      0.92      0.90        92
         Lab       0.57      0.62      0.59        13
     Similar       0.65      1.00      0.79        70

    accuracy                           0.81       290
   macro avg       0.62      0.69      0.64       290
weighted avg       0.74      0.81      0.76       290



In [22]:
print(confusion_matrix(y_test,predictions))

[[ 0  0  0  0 35]
 [ 0 71  9  0  0]
 [ 0  0 85  6  1]
 [ 1  0  3  8  1]
 [ 0  0  0  0 70]]
