In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
data=pd.read_excel("../data/PM_ML_Data_Final.xlsx",index_col="TestID")

In [3]:
data.head()

WNRD     WNVol     WNNCD    Class
TestID                                       
1       0.000120  0.012339  0.008525  Similar
2       0.000120  0.011953  0.008375  Similar
3       0.000196  0.007618  0.004438  Similar
4       0.000197  0.007452  0.004424  Similar
5       0.000162  0.012785  0.009120  Similar

## Data Split

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
seed=7

In [6]:
X=data.drop('Class',axis=1)
y=data['Class']

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=seed)

## QDA

In [8]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA

In [9]:
qda=QDA()

In [10]:
qda.fit(X_train,y_train)

QuadraticDiscriminantAnalysis()

In [11]:
print(qda.score(X_train,y_train))

0.9452662721893491


## Prediction

In [12]:
qda.predict(X_test)

array(['Different', 'Instrument', 'Instrument', 'Similar', 'Different',
       'Different', 'Different', 'Instrument', 'Different', 'Day',
       'Instrument', 'Similar', 'Instrument', 'Instrument', 'Similar',
       'Lab', 'Different', 'Instrument', 'Similar', 'Day', 'Similar',
       'Instrument', 'Day', 'Similar', 'Day', 'Instrument', 'Different',
       'Lab', 'Different', 'Different', 'Different', 'Similar', 'Day',
       'Similar', 'Similar', 'Different', 'Instrument', 'Day', 'Day',
       'Different', 'Similar', 'Similar', 'Day', 'Day', 'Instrument',
       'Different', 'Similar', 'Different', 'Instrument', 'Instrument',
       'Different', 'Day', 'Similar', 'Similar', 'Day', 'Instrument',
       'Different', 'Lab', 'Different', 'Day', 'Different', 'Different',
       'Instrument', 'Instrument', 'Similar', 'Instrument', 'Instrument',
       'Instrument', 'Instrument', 'Instrument', 'Similar', 'Different',
       'Instrument', 'Instrument', 'Similar', 'Similar', 'Instrument',
   

## Evaluation

In [13]:
predictions=qda.predict(X_test)

In [14]:
from sklearn.metrics import classification_report,confusion_matrix

In [15]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         Day       0.72      0.80      0.76        35
   Different       1.00      1.00      1.00        80
  Instrument       1.00      0.99      0.99        92
         Lab       1.00      1.00      1.00        13
     Similar       0.88      0.84      0.86        70

    accuracy                           0.93       290
   macro avg       0.92      0.93      0.92       290
weighted avg       0.94      0.93      0.94       290



In [16]:
print(confusion_matrix(y_test,predictions))

[[28  0  0  0  7]
 [ 0 80  0  0  0]
 [ 0  0 91  0  1]
 [ 0  0  0 13  0]
 [11  0  0  0 59]]


## Unknown Predictions

In [21]:
un=pd.read_excel("../data/PM_ML_Unknown.xlsx",index_col="TestID")

In [22]:
un

WNRD     WNVol     WNNCD
TestID                              
14      0.000206  0.019164  0.012985
70      0.000307  0.008519  0.009125
176     0.192594  0.087238  0.208814
295     0.199662  0.149283  0.246484
382     0.001103  0.047906  0.036669
419     0.002454  0.099070  0.057033
425     0.006560  0.139213  0.094563
723     0.006616  0.149104  0.099622
731     0.000245  0.024575  0.018870
833     0.000363  0.010278  0.008227

In [18]:
un_prediction=qda.predict(un)

In [19]:
un["Prediction"]=un_prediction[:]

In [20]:
un

WNRD     WNVol     WNNCD  Prediction
TestID                                          
14      0.000206  0.019164  0.012985     Similar
70      0.000307  0.008519  0.009125     Similar
176     0.192594  0.087238  0.208814   Different
295     0.199662  0.149283  0.246484   Different
382     0.001103  0.047906  0.036669         Lab
419     0.002454  0.099070  0.057033         Lab
425     0.006560  0.139213  0.094563  Instrument
723     0.006616  0.149104  0.099622  Instrument
731     0.000245  0.024575  0.018870         Day
833     0.000363  0.010278  0.008227         Day