In [1]:
import numpy as np
import pandas as pd

## import module

In [2]:
from sklearn import model_selection

In [3]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

## 데이터 불러오기

In [5]:
df=pd.read_excel("../data/PM_ML_Data_Final.xlsx",index_col="TestID")

In [6]:
df.head()

WNRD     WNVol     WNNCD    Class
TestID                                       
1       0.000120  0.012339  0.008525  Similar
2       0.000120  0.011953  0.008375  Similar
3       0.000196  0.007618  0.004438  Similar
4       0.000197  0.007452  0.004424  Similar
5       0.000162  0.012785  0.009120  Similar

## 데이터 나누기

In [7]:
test_size=0.3
score='accuracy'

## 다른 알고리즘 적용하기

In [8]:
def models(X_train,y_train,score):
    clfs=[]
    result=[]
    names=[]
    clfs.append(('LR',LogisticRegression()))
    clfs.append(('LDA',LinearDiscriminantAnalysis()))
    clfs.append(('KNN',KNeighborsClassifier()))
    clfs.append(('TREE',DecisionTreeClassifier()))
    clfs.append(('NB',GaussianNB()))
    clfs.append(('SVC',SVC()))
    for algo_name, clf in clfs:
        k_fold=model_selection.KFold(n_splits=10,random_state=7)
        cv_score=model_selection.cross_val_score(clf,X_train,y_train,cv=k_fold,scoring=score)
        result.append((algo_name,cv_score.mean(),cv_score.std()))
        names.append(algo_name)
    return(result)

In [9]:
X_all=df.iloc[:,:3]

In [10]:
X_all.head()

WNRD     WNVol     WNNCD
TestID                              
1       0.000120  0.012339  0.008525
2       0.000120  0.011953  0.008375
3       0.000196  0.007618  0.004438
4       0.000197  0.007452  0.004424
5       0.000162  0.012785  0.009120

In [11]:
y_all=df.iloc[:,3]

In [12]:
y_all.head()

TestID
1    Similar
2    Similar
3    Similar
4    Similar
5    Similar
Name: Class, dtype: object

In [13]:
seed=7

In [14]:
X_train_all,X_test_all,y_train_all,y_test_all=model_selection.train_test_split(X_all,y_all,test_size=test_size,random_state=seed)

## 알고리즘 돌리기

In [15]:
models(X_train_all,y_train_all,score)

C:\Users\jksuh\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(
C:\Users\jksuh\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(
C:\Users\jksuh\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  warnings.warn(
C:\Users\jksuh\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:293: FutureWarning: Setting a random_state has no effect since shuffle is 

[('LR', 0.8328797190517998, 0.06352892885888496),
 ('LDA', 0.8268656716417911, 0.04814637232133729),
 ('KNN', 0.9378402107111501, 0.03728550832388731),
 ('TREE', 0.9348551360842846, 0.02125591155974727),
 ('NB', 0.8979587357330991, 0.03180094214241445),
 ('SVC', 0.8402326602282704, 0.060380589500532836)]

In [16]:
KNN=KNeighborsClassifier()
KNN.fit(X_train_all,y_train_all)

KNeighborsClassifier()

In [17]:
predictions=KNN.predict(X_test_all)

In [19]:
print(accuracy_score(y_test_all,predictions))

0.9310344827586207


In [20]:
print(confusion_matrix(y_test_all,predictions))

[[28  0  0  0  7]
 [ 0 80  0  0  0]
 [ 0  0 91  0  1]
 [ 0  0  4  9  0]
 [ 8  0  0  0 62]]


In [21]:
print(classification_report(y_test_all,predictions))

              precision    recall  f1-score   support

         Day       0.78      0.80      0.79        35
   Different       1.00      1.00      1.00        80
  Instrument       0.96      0.99      0.97        92
         Lab       1.00      0.69      0.82        13
     Similar       0.89      0.89      0.89        70

    accuracy                           0.93       290
   macro avg       0.92      0.87      0.89       290
weighted avg       0.93      0.93      0.93       290

