In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel("../data/PM_ML_Data_Final.xlsx",index_col="TestID")

In [3]:
df.head()

WNRD     WNVol     WNNCD    Class
TestID                                       
1       0.000120  0.012339  0.008525  Similar
2       0.000120  0.011953  0.008375  Similar
3       0.000196  0.007618  0.004438  Similar
4       0.000197  0.007452  0.004424  Similar
5       0.000162  0.012785  0.009120  Similar

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
X=df.drop('Class',axis=1)

In [7]:
y=df['Class']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=7)

In [10]:
from sklearn.svm import SVC

In [11]:
svc_model=SVC()

In [12]:
svc_model.fit(X_train,y_train)

SVC()

In [13]:
predictions=svc_model.predict(X_test)

In [14]:
from sklearn.metrics import classification_report,confusion_matrix

In [15]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         Day       0.00      0.00      0.00        35
   Different       1.00      1.00      1.00        80
  Instrument       0.91      0.99      0.95        92
         Lab       1.00      0.15      0.27        13
     Similar       0.65      1.00      0.79        70

    accuracy                           0.84       290
   macro avg       0.71      0.63      0.60       290
weighted avg       0.77      0.84      0.78       290



C:\Users\jksuh\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
print(confusion_matrix(y_test,predictions))

[[ 0  0  0  0 35]
 [ 0 80  0  0  0]
 [ 0  0 91  0  1]
 [ 0  0  9  2  2]
 [ 0  0  0  0 70]]


In [19]:
print("훈련정확도: {:.3f}".format(svc_model.score(X_train,y_train)))

훈련정확도: 0.849


In [20]:
print("예측정확도: {:.3f}".format(svc_model.score(X_test,y_test)))

예측정확도: 0.838


In [21]:
un=pd.read_excel("../data/PM_ML_Unknown.xlsx",index_col="TestID")

In [22]:
un_prediction=svc_model.predict(un)

In [23]:
un_prediction

array(['Similar', 'Similar', 'Different', 'Different', 'Lab',
       'Instrument', 'Instrument', 'Instrument', 'Similar', 'Similar'],
      dtype=object)

In [24]:
un["Predition"]=un_prediction[:]

In [25]:
un

WNRD     WNVol     WNNCD   Predition
TestID                                          
14      0.000206  0.019164  0.012985     Similar
70      0.000307  0.008519  0.009125     Similar
176     0.192594  0.087238  0.208814   Different
295     0.199662  0.149283  0.246484   Different
382     0.001103  0.047906  0.036669         Lab
419     0.002454  0.099070  0.057033  Instrument
425     0.006560  0.139213  0.094563  Instrument
723     0.006616  0.149104  0.099622  Instrument
731     0.000245  0.024575  0.018870     Similar
833     0.000363  0.010278  0.008227     Similar

In [26]:
un.to_csv("../data/PM_ML_SVC_Unknown_Prediction.csv")